tidyNottem <- function(temperatures) {
  timetk::tk_tbl(temperatures) %>%
    tidyr::separate(col = index, # index automatically generated by tk_tbl()
             into = c("month","year"),
             sep = " ")
}

