temperatureSeriesToDf <- function(temperature_series) {
  timetk::tk_tbl(temperature_series)
}

tidyTemperatures <- function(temperatures) {
  temperatures %>%
    tidyr::separate(col = index,
                    # index automatically generated by tk_tbl()
                    into = c("month", "year"),
                    sep = " ")
}
